# Generated by Django 4.2.4 on 2023-08-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreClasificacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTipoPaciente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.IntegerField()),
                ('FechaFallecimiento', models.DateField(blank=True, null=True)),
                ('Sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidstats.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='DatosSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neumonia', models.IntegerField()),
                ('Embarazo', models.IntegerField()),
                ('Diabetes', models.IntegerField()),
                ('COPD', models.IntegerField()),
                ('Asma', models.IntegerField()),
                ('Inmunodepresion', models.IntegerField()),
                ('Hipertension', models.IntegerField()),
                ('EnfermedadCardiovascular', models.IntegerField()),
                ('EnfermedadRenalCronica', models.IntegerField()),
                ('OtraEnfermedad', models.IntegerField()),
                ('Obesidad', models.IntegerField()),
                ('Tabaco', models.IntegerField()),
                ('USMR', models.IntegerField()),
                ('Intubado', models.IntegerField()),
                ('UCI', models.IntegerField()),
                ('Clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidstats.clasificacion')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidstats.paciente')),
                ('TipoPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidstats.tipopaciente')),
            ],
        ),
    ]
